// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthHealthCheckResponse, RootRootResponse, UserApiGetUsersResponse } from './types.gen';

export class HealthService {
    /**
     * Health Check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<HealthHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
}

export class RootService {
    /**
     * Root
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static root(): CancelablePromise<RootRootResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
}

export class UserService {
    /**
     * Api Get Users
     * @returns User Successful Response
     * @throws ApiError
     */
    public static apiGetUsers(): CancelablePromise<UserApiGetUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/'
        });
    }
}