// This file is auto-generated by @hey-api/openapi-ts

export type User = {
    created_at?: string;
    updated_at?: string;
    id?: string;
    email: string;
    first_name?: (string | null);
    last_name?: (string | null);
    password: string;
    is_active?: boolean;
    is_superuser?: boolean;
};

export type HealthHealthCheckResponse = (unknown);

export type RootRootResponse = (unknown);

export type UserApiGetUsersResponse = (Array<User>);