"""change user id to uuid

Revision ID: ffa0d86da885
Revises: 5ecd1e887693
Create Date: 2025-09-27 23:49:21.739003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffa0d86da885'
down_revision: Union[str, Sequence[str], None] = '5ecd1e887693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
